project:
  type: book
  output-dir: docs

website:
  site-url: "https://stdfreesince03.github.io/18222061-AsesmenII2100"
  
book:
  title: "Winata Tristan"
  subtitle: "Portfolio Asesmen II-2100 KIPP"
  author: "18222061 Winata Tristan"
  date: "10/13/2025"
  chapters:
    - index.qmd
    - My_Song_for_You/index.qmd
    - My_Stories_for_You/index.qmd
    - My_Shapes/index.qmd
    - My_Personal_Reviews/index.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    theme:
      - cosmo
      - brand
    include-in-header:
      text: |
        <style>
          /* justify body text only (not navbar/sidebar) */
          main.content p { 
            text-align: justify; 
            text-justify: inter-word; 
            hyphens: auto;
          }
          main.content li {
            text-align: justify; 
            text-justify: inter-word; 
            hyphens: auto;
          }
          main.content img {
          display: block;
          margin-left: auto;
          margin-right: auto;
        }
        .quarto-figure, figure {
          text-align: center;
        }
        </style>
  pdf:
    documentclass: scrreprt



